// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpcyjpdylovsnbxfyyqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY3lqcGR5bG92c25ieGZ5eXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2ODExMTksImV4cCI6MjA3MDI1NzExOX0.2nloT0vMywlW0Ff4_en8ls6urup7Y-hFnWwiZdUQbQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});